# Generated by Django 3.1.7 on 2021-02-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('movement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_at', to='app.location')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductMovement', to='app.product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_to_be', to='app.location')),
            ],
        ),
    ]
