# Generated by Django 3.1.7 on 2021-02-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210226_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location_at', to='app.location'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location_to_be', to='app.location'),
        ),
    ]
