# Generated by Django 3.1.7 on 2021-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210226_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_qty',
            field=models.IntegerField(default=0),
        ),
    ]
