# Generated by Django 3.1.7 on 2021-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_pro_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
