# Generated by Django 3.1.7 on 2021-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
